import fs from 'node:fs'; import assert from 'node:assert/strict';
const copilot=fs.readFileSync(new URL('../public/lib/workflow-copilot.js',import.meta.url),'utf8');
const builder=fs.readFileSync(new URL('../public/lib/recipe-builder-2.js',import.meta.url),'utf8');
const home=fs.readFileSync(new URL('../public/app/index.html',import.meta.url),'utf8');
assert.match(copilot,/function normalizeDefinition/);
assert.match(copilot,/out\.version = 2/);
assert.match(copilot,/out\.goal =/);
assert.match(copilot,/description:s\.description \|\| meta\[1\]/);
assert.match(copilot,/executeDefinition\(definition\)/);
assert.match(copilot,/pipeline_prompt_submitted/);
assert.match(copilot,/pipeline_built/);
assert.match(copilot,/pipeline_run_success/);
assert.match(copilot,/pipeline_saved/);
assert.match(copilot,/pipeline_deploy_clicked/);
assert.match(builder,/async function executeDefinition\(definition\)/);
assert.match(builder,/executeDefinition: executeDefinition/);
assert.doesNotMatch(builder,/setTimeout\(\(\) => runFullPreview\(\), 20\)/);
assert.match(home,/id="wcBuildBtn">Build pipeline/);
assert.match(home,/id="wcRunBtn"[^>]*>Run pipeline/);
assert.match(home,/id="wcOpenBtn"[^>]*>Edit pipeline/);
console.log('Recast 2A vertical-slice wiring passed');
