const SITE = 'https://tryrecast.app';

export const SEO_PAGES = {
  'json-api-to-csv': {cluster:'Convert',title:'JSON API to CSV — Convert API Data for Excel | Recast',description:'Convert captured JSON API data to CSV, flatten nested fields and move repeat exports into a Recast workflow or API integration.',h1:'Convert JSON API data to CSV',intent:'Export structured API responses into spreadsheet-ready rows without maintaining a one-off script.',tool:'/tools/api-response-to-csv.html',next:'/use-cases/api-response-to-csv.html',example:'A REST response contains customer.name and customer.city inside nested objects. Flatten those paths, then convert the resulting records to CSV columns.',limit:'Arrays with multiple child records may need reshaping before a useful one-row-per-record CSV can be produced.',steps:['Paste a captured JSON API response into the browser tool.','Flatten nested fields when the response shape requires it.','Convert to CSV, inspect the columns and download the result.']},
  'csv-to-json-api-payload': {cluster:'Convert',title:'CSV to JSON for API Payloads | Recast',description:'Convert CSV exports into structured JSON for APIs, preserving useful types and moving repeated conversion into a reusable workflow.',h1:'Convert CSV into JSON for an API payload',intent:'Turn rows from spreadsheets or exports into structured JSON that is easier to send to an API or application.',tool:'/tools/csv-to-json.html',next:'/app/#workflowBuilder',example:'A CSV export with id, active and total columns can become an array of JSON objects, with type inference enabled when the values are consistently typed.',limit:'CSV cannot represent every nested JSON structure directly, so deeply nested target payloads may need an additional transformation step.',steps:['Paste or load CSV into the converter.','Choose delimiter and type-inference options.','Inspect the generated JSON before passing it to the next system.']},
  'json-to-yaml-config': {cluster:'Convert',title:'JSON to YAML for Configuration Files | Recast',description:'Convert JSON configuration data to YAML in the browser and reuse the same conversion in a Recast workflow when it becomes repetitive.',h1:'Convert JSON configuration to YAML',intent:'Move structured configuration between JSON and YAML without reformatting it manually.',tool:'/tools/json-to-yaml.html',next:'/app/#workflowBuilder',example:'A JSON configuration object containing service, region and nested feature flags can be converted to readable YAML while preserving the underlying structure.',limit:'Comments present in an original YAML document cannot be recreated from JSON because JSON has no equivalent comment data.',steps:['Paste valid JSON into the JSON to YAML tool.','Run the conversion and inspect indentation and scalar values.','Copy or download the YAML, or save the operation as part of a workflow.']},
  'flatten-nested-json-for-csv': {cluster:'Transform',title:'Flatten Nested JSON for CSV Export | Recast',description:'Flatten nested JSON into predictable dotted fields before CSV export, keeping one-off work local and repeat transformations reusable.',h1:'Flatten nested JSON before exporting to CSV',intent:'Turn deeply nested objects into flat fields that are easier to inspect, export and compare.',tool:'/tools/flatten-json.html',next:'/tools/json-to-csv.html',example:'An address object becomes fields such as address.city and address.country, which can then map cleanly into CSV columns.',limit:'Flattening changes the shape of the data. Keep a copy of the original structure when downstream systems still need nested objects.',steps:['Inspect the nested JSON structure.','Flatten objects into dotted paths.','Convert the flattened result to CSV if a tabular export is required.']},
  'extract-jsonpath-api-response': {cluster:'Transform',title:'Extract Data from an API Response with JSONPath | Recast',description:'Test JSONPath against captured API responses, extract the records you need and reuse the extraction as part of a Recast workflow.',h1:'Extract records from an API response with JSONPath',intent:'Select only the fields or records needed from a larger JSON response before conversion, validation or export.',tool:'/tools/jsonpath-tester.html',next:'/app/#workflowBuilder',example:'From an orders response, a JSONPath expression can select the order records or a nested field such as every customer name.',limit:'JSONPath expressions depend on the input structure. A schema change in the upstream API can require the expression to be updated.',steps:['Paste the captured JSON response.','Test a JSONPath expression against the real structure.','Use the extracted result in the next transformation or save the step in a workflow.']},
  'validate-api-json': {cluster:'Validate',title:'Validate API JSON Before Processing | Recast',description:'Validate JSON API payloads in the browser, identify syntax problems quickly and move recurring validation into a workflow or hosted API path.',h1:'Validate API JSON before it reaches the next system',intent:'Catch malformed JSON early rather than discovering it later in an integration or pipeline.',tool:'/tools/json-validator.html',next:'/use-cases/automated-data-validation.html',example:'A captured payload with a missing quote or trailing comma can be checked before it is sent to another API or imported downstream.',limit:'Syntax validation confirms that JSON is well formed; it does not prove that the payload matches a business contract or JSON Schema.',steps:['Paste the JSON payload into the validator.','Run validation and fix any syntax errors.','Use JSON Schema validation as a separate step when structural rules also matter.']},
  'validate-json-schema-api-payload': {cluster:'Validate',title:'Validate an API Payload Against JSON Schema | Recast',description:'Check JSON API data against JSON Schema, inspect violations and reuse the validation step in workflows or hosted execution.',h1:'Validate an API payload against JSON Schema',intent:'Check whether real JSON conforms to a documented structure before it enters production systems.',tool:'/tools/validate-json-schema.html',next:'/use-cases/automated-data-validation.html',example:'A schema can require an id to be an integer and status to be a string; Recast reports when a supplied payload violates those constraints.',limit:'A schema only enforces the rules it contains. Business rules that are not represented in the schema need separate checks.',steps:['Provide the JSON Schema and the payload to validate.','Run the structural check and review each violation.','Add the validation step to a repeatable workflow if the same contract is checked regularly.']},
  'compare-api-responses': {cluster:'Compare',title:'Compare API Responses and Find Structural Changes | Recast',description:'Compare JSON API responses structurally to find added, removed and changed values without relying on noisy line-by-line diffs.',h1:'Compare API responses structurally',intent:'See meaningful changes between environments, API versions or test runs even when formatting or array order changes.',tool:'/tools/compare-api-responses.html',next:'/tools/json-diff.html',example:'Compare a staging response with production to spot a removed field, changed type or newly added property before an integration is released.',limit:'A structural diff shows what changed; deciding whether a change is safe still depends on the consuming application and its contract.',steps:['Capture the two API responses you want to compare.','Run a structural comparison instead of a text-only diff.','Review added, removed and changed paths before deciding what needs action.']},
  'automate-json-csv-conversion': {cluster:'Automate',title:'Automate Recurring JSON to CSV Conversion | Recast',description:'Build a reusable JSON to CSV workflow, then move to hosted Recast Automation when the same transformation must run unattended.',h1:'Automate recurring JSON to CSV conversion',intent:'Replace repeated manual conversion with a reusable workflow and, when needed, hosted execution.',tool:'/tools/json-to-csv.html',next:'/automation/json-to-csv-automation.html',example:'A daily JSON export can use the same flatten-and-convert sequence each time instead of requiring a developer to rerun a script manually.',limit:'Browser workflows remain local. Scheduled or webhook-triggered execution is hosted, so supplied input is sent to Recast for server-side processing.',steps:['Prove the conversion in the browser tool.','Save the operation as part of a Recast workflow.','Choose hosted Automation only when the workflow must run without an open browser.']},
  'schedule-data-validation': {cluster:'Automate',title:'Schedule Recurring Data Validation | Recast',description:'Turn repeated JSON or schema checks into a reusable workflow and use hosted Automation when validation needs to run on a schedule.',h1:'Schedule recurring data validation',intent:'Run the same validation rules repeatedly without relying on someone to open the browser and trigger them manually.',tool:'/tools/validate-json-schema.html',next:'/automation/',example:'A nightly payload can be checked against the same JSON Schema before the next system consumes it.',limit:'Scheduled validation requires hosted execution. Inputs for those runs are processed server-side rather than staying entirely in the browser.',steps:['Confirm the validation rule with representative data locally.','Save the validation as a workflow.','Configure a hosted schedule only after reviewing the processing boundary.']},
  'recast-api-data-conversion': {cluster:'API',title:'Recast API for Data Conversion | JSON, CSV, XML, YAML',description:'Use documented Recast API endpoints for supported data conversion operations after prototyping the same job in the browser.',h1:'Use the Recast API for supported data conversion',intent:'Put proven conversion operations into backends, internal tools or scripts through documented HTTP endpoints.',tool:'/api/index.html',next:'/use-cases/api-for-internal-tools.html',example:'A backend can call POST /v1/convert with mode json2csv after the same conversion has been tested interactively in the browser.',limit:'The API is hosted execution. Request data is sent to Recast for server-side processing and only documented modes should be relied on.',steps:['Prototype the operation with the matching browser tool.','Review the documented API endpoint and supported mode.','Send authenticated requests from the system that needs hosted conversion.']},
  'recast-api-ci-cd': {cluster:'API',title:'Use the Recast API in CI/CD Pipelines | Recast',description:'Use supported Recast API operations in CI/CD for repeatable conversion or validation, with clear hosted-processing boundaries.',h1:'Use Recast in a CI/CD data pipeline',intent:'Run deterministic data checks or conversions as part of an automated build or delivery process.',tool:'/api/index.html',next:'/use-cases/api-for-ci-cd.html',example:'A pipeline can validate generated JSON or perform a documented conversion before publishing an artifact to the next environment.',limit:'For files that must never leave the runner, prefer the local recast-cli path; API calls are hosted and send request data to Recast.',steps:['Test the operation interactively or with the local CLI.','Choose the documented API endpoint only when hosted execution is acceptable.','Fail the pipeline on API or validation errors rather than ignoring them.']}
};

function esc(v) { return String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function slugUrl(slug) { return `${SITE}/seo/${slug}.html`; }
function related(slug, page) { return Object.entries(SEO_PAGES).filter(([s,p]) => s !== slug && p.cluster === page.cluster).slice(0,3); }

export function renderSeoPage(slug) {
  const page = SEO_PAGES[slug];
  if (!page) return null;
  const canonical = slugUrl(slug);
  const crumbs = {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':`${SITE}/`},{'@type':'ListItem','position':2,'name':'SEO guides','item':`${SITE}/seo/`},{'@type':'ListItem','position':3,'name':page.h1,'item':canonical}]};
  const faq = {'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':`Can I do this in the browser first?`,'acceptedAnswer':{'@type':'Answer','text':'Yes. Recast browser tools are designed for immediate local use. Hosted API or Automation execution is a separate, explicit step.'}},{'@type':'Question','name':'What should I watch for?','acceptedAnswer':{'@type':'Answer','text':page.limit}}]};
  const rel = related(slug,page).map(([s,p]) => `<a href="/seo/${s}.html">${esc(p.h1)}</a>`).join(' · ');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(page.title)}</title><meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify(crumbs)}</script><script type="application/ld+json">${JSON.stringify(faq)}</script></head><body><main style="max-width:900px;margin:0 auto;padding:48px 24px"><nav><a href="/">Home</a> › <a href="/seo/">SEO guides</a> › ${esc(page.cluster)}</nav><p class="eyebrow">${esc(page.cluster)} · developer data workflow</p><h1>${esc(page.h1)}</h1><p>${esc(page.intent)}</p><h2>How to do it with Recast</h2><ol>${page.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h2>Example</h2><p>${esc(page.example)}</p><h2>Limitation to understand</h2><p>${esc(page.limit)}</p><h2>Choose the right execution path</h2><p>Use the browser tool for immediate local work. If the operation becomes repeatable, move it into a Recast workflow. Choose hosted Automation or the API only when server-side execution is explicitly required.</p><p><a href="${esc(page.tool)}">Start with the relevant Recast tool →</a></p><p><a href="${esc(page.next)}">Continue to the workflow or commercial path →</a></p><h2>Related ${esc(page.cluster)} guides</h2><p>${rel || '<a href="/seo/">Browse all Recast SEO guides</a>'}</p><p><a href="/tools/index.html">Tools</a> · <a href="/app/">Workflows</a> · <a href="/automation/">Automation</a> · <a href="/api/index.html">API</a></p></main></body></html>`;
}

export function renderSeoIndex() {
  const groups = {};
  for (const [slug,page] of Object.entries(SEO_PAGES)) (groups[page.cluster] ||= []).push([slug,page]);
  const sections = Object.entries(groups).map(([cluster,rows]) => `<section><h2>${esc(cluster)}</h2><ul>${rows.map(([slug,p])=>`<li><a href="/seo/${slug}.html">${esc(p.h1)}</a> — ${esc(p.description)}</li>`).join('')}</ul></section>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recast Developer Data Guides — Convert, Transform, Validate, Automate</title><meta name="description" content="High-intent Recast guides for conversion, transformation, validation, comparison, Automation and API workflows."><link rel="canonical" href="${SITE}/seo/"><link rel="stylesheet" href="/styles.css"></head><body><main style="max-width:900px;margin:0 auto;padding:48px 24px"><a href="/">← Recast</a><h1>Developer data guides</h1><p>Practical pages organised by the job you need to complete, with a direct path into the relevant Recast tool, workflow, Automation or API capability.</p>${sections}</main></body></html>`;
}
