(()=>{
  const fit=()=>{
    const img=[...document.querySelectorAll('img')].find(x=>/homepage-graphic\.png/i.test(x.getAttribute('src')||''));
    if(!img)return;
    const art=img.parentElement;
    if(!art)return;
    art.style.setProperty('aspect-ratio','1 / 1','important');
    art.style.setProperty('max-height','none','important');
    art.style.setProperty('overflow','hidden','important');
    art.style.setProperty('background','#eef8f4','important');
    art.style.setProperty('display','flex','important');
    art.style.setProperty('align-items','center','important');
    art.style.setProperty('justify-content','center','important');
    img.style.setProperty('position','static','important');
    img.style.setProperty('display','block','important');
    img.style.setProperty('width','92%','important');
    img.style.setProperty('height','92%','important');
    img.style.setProperty('max-width','92%','important');
    img.style.setProperty('object-fit','contain','important');
    img.style.setProperty('object-position','center center','important');
    img.style.setProperty('transform','none','important');
    img.style.setProperty('left','auto','important');
    img.style.setProperty('top','auto','important');
    img.style.setProperty('margin','auto','important');
  };
  const run=()=>requestAnimationFrame(fit);
  new MutationObserver(run).observe(document.documentElement,{childList:true,subtree:true});
  addEventListener('resize',run,{passive:true});
  run();
})();
