(()=>{
const OFFER_ID='hqc-decision-pack-offer',CASE='hqcDecisionPackCaseId',PAID='hqcDecisionPackPaid',EVENT='/api/event';
const qa=/[?&](?:qa|release_probe|upload_handoff_smoke)=/i.test(location.search);
const caseId=(()=>{let v=localStorage.getItem(CASE);if(!v){v=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem(CASE,v)}return v})();
const readQuotes=()=>{try{return JSON.parse(localStorage.getItem('hqc_case')||'[]')}catch{return[]}};
const event=async(name,extra={})=>{try{await fetch(EVENT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:name,caseId,isTest:qa,...extra}),keepalive:true})}catch{}};
const paid=()=>{try{return JSON.parse(localStorage.getItem(PAID)||'null')?.caseId===caseId}catch{return false}};
const setPaid=s=>localStorage.setItem(PAID,JSON.stringify({caseId,sessionId:s,paidAt:new Date().toISOString()}));
const hasCase=()=>/your decision case|decision case/i.test(document.body?.innerText||'');
const missing=(q,k)=>q?.[k]==null||q[k]===''||/not found|not provided|not evidenced|unknown/i.test(String(q[k]));
function analysis(){const quotes=readQuotes();const names=quotes.map((q,i)=>q.installer||q.fileName||`Quote ${i+1}`);const priced=quotes.filter(q=>Number(q.price)>0).sort((a,b)=>Number(a.price)-Number(b.price));const issues=[];quotes.forEach((q,i)=>{const n=names[i];if(missing(q,'heatLossKw'))issues.push(`${n}: whole-home heat loss is not evidenced.`);if(missing(q,'roomByRoom'))issues.push(`${n}: room-by-room heat-loss evidence is not clear.`);if(missing(q,'flowTemperatureC'))issues.push(`${n}: design flow temperature is not stated.`);if(missing(q,'emitterChanges'))issues.push(`${n}: radiator/emitter treatment is not clear.`);if(missing(q,'model'))issues.push(`${n}: exact heat-pump model is not clear.`)});let position='Do not choose on headline price alone.';if(priced.length>1){const gap=Number(priced.at(-1).price)-Number(priced[0].price);position=`${priced[0].installer||priced[0].fileName||'The lowest quote'} is £${Math.round(gap).toLocaleString('en-GB')} cheaper on the stated prices, but confirm the scopes are genuinely like-for-like before treating that as a saving.`}else if(quotes.length===1)position='This quote can be assessed for gaps, but a second genuine quote would strengthen the commercial comparison.';const per=quotes.map((q,i)=>{const n=names[i],actions=[];if(missing(q,'heatLossKw')||missing(q,'roomByRoom'))actions.push('Provide the heat-loss calculation, including room-by-room figures and design assumptions.');if(missing(q,'flowTemperatureC'))actions.push('Confirm the design flow temperature and the emitter outputs used at that temperature.');if(missing(q,'emitterChanges'))actions.push('Confirm every radiator/emitter change and whether it is included in the fixed price.');actions.push('Confirm all exclusions, provisional sums, electrical works, commissioning and handover items in writing.');return {name:n,actions}});return {quotes,names,issues:[...new Set(issues)].slice(0,8),position,per};}
function detailedMarkup(){const a=analysis();return `<div style="font-size:13px;font-weight:800;letter-spacing:.06em;color:#2f6c5a;text-transform:uppercase">Personalised decision analysis</div><h2 style="margin:6px 0 8px">Your Decision Pack</h2><div style="padding:14px;border-radius:12px;background:#eef8f4;margin:12px 0"><b>Current position</b><p style="margin:6px 0 0;line-height:1.5">${a.position}</p></div><h3>Material points to resolve</h3><ul>${(a.issues.length?a.issues:['No major evidence gap was detected in the extracted fields; confirm scope, exclusions and design assumptions before signing.']).map(x=>`<li>${x}</li>`).join('')}</ul><h3>What each installer needs to answer</h3>${a.per.map(x=>`<div style="margin:12px 0;padding:14px;border:1px solid #d8e8e1;border-radius:12px"><b>${x.name}</b><ol>${x.actions.map(y=>`<li>${y}</li>`).join('')}</ol></div>`).join('')}<div style="padding:14px;border-left:4px solid #087f5b;background:#f7faf9;margin:16px 0"><b>Decision condition</b><p style="margin:5px 0 0">Do not rely on the apparent price advantage until the material gaps above are answered in writing and the final included scope is confirmed.</p></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button data-hqc-questions>Copy personalised questions</button><button data-hqc-print>Print Decision Pack</button></div><div data-hqc-note style="font-size:12px;color:#617187;margin-top:12px">Independent evidence-based decision support — not design certification, installer approval or confirmation of grant eligibility.</div>`}
function questions(){return analysis().per.flatMap(x=>x.actions.map(y=>`${x.name}: ${y}`))}
function printPack(){const a=analysis(),w=open('','_blank');if(!w)return;const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');w.document.write(`<html><head><title>Home Quote Check Decision Pack</title><style>body{font:15px/1.55 system-ui;max-width:820px;margin:40px auto;padding:0 24px;color:#17352d}h1{font-size:30px}h2{margin-top:28px}section{margin:18px 0;padding:16px;background:#f5faf7;border-radius:12px}</style></head><body><h1>Home Quote Check Decision Pack</h1><section><b>Current position</b><p>${esc(a.position)}</p></section><h2>Material points to resolve</h2><ul>${a.issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Installer-specific actions</h2>${a.per.map(x=>`<h3>${esc(x.name)}</h3><ol>${x.actions.map(y=>`<li>${esc(y)}</li>`).join('')}</ol>`).join('')}<h2>Decision condition</h2><p>Resolve the material gaps in writing and confirm the final included scope before relying on the apparent price advantage or paying a deposit.</p><p><small>Independent evidence-based support only — not design certification, installer approval or grant-eligibility confirmation.</small></p><script>print()<\/script></body></html>`);w.document.close();event('decision_case_downloaded',{product:'decision_pack'})}
const offerMarkup=()=>`<div style="font-size:13px;font-weight:800;letter-spacing:.06em;color:#2f6c5a;text-transform:uppercase">Ready to choose?</div><div style="font-weight:850;font-size:24px;margin:5px 0 8px">Get your personalised Decision Pack — £19</div><div style="color:#365b50;line-height:1.5;margin-bottom:12px">Turn your free quote comparison into a detailed decision analysis built from your actual proposals.</div><ul style="margin:0 0 15px;padding-left:20px;color:#365b50"><li>Detailed quote-by-quote analysis of material gaps and commercial risks</li><li>Separate, personalised questions for each installer</li><li>Clear conditions to resolve before choosing or paying a deposit</li><li>Printable Decision Pack to use through the installer conversation</li></ul><button data-hqc-buy style="width:100%;border:0;border-radius:12px;padding:14px 18px;background:#183f34;color:white;font-size:16px;font-weight:800;cursor:pointer">Get my personalised Decision Pack — £19</button><div data-hqc-pay-status style="font-size:13px;color:#56756c;margin-top:10px">One-off payment · No subscription · Secure checkout by Stripe</div>`;
function bind(box){box.querySelector('[data-hqc-buy]')?.addEventListener('click',async e=>{const btn=e.currentTarget,status=box.querySelector('[data-hqc-pay-status]');btn.disabled=true;btn.textContent='Opening secure checkout…';event('decision_pack_checkout_started',{price_gbp:19});try{const r=await fetch('/api/decision-pack/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({caseId})}),d=await r.json();if(!r.ok||!d.url)throw 0;location.href=d.url}catch{status.textContent='Checkout is temporarily unavailable. Please try again.';btn.disabled=false;btn.textContent='Get my personalised Decision Pack — £19'}});box.querySelector('[data-hqc-questions]')?.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(questions().map((q,i)=>`${i+1}. ${q}`).join('\n'));e.currentTarget.textContent='Personalised questions copied';event('installer_questions_generated',{product:'decision_pack',count:questions().length})}catch{}});box.querySelector('[data-hqc-print]')?.addEventListener('click',printPack)}
function render(){if(!hasCase()&&!paid())return;const state=paid()?'paid':'offer';let box=document.getElementById(OFFER_ID);if(!box){box=document.createElement('section');box.id=OFFER_ID;box.style.cssText='max-width:760px;margin:24px auto;padding:20px;border:1px solid #cfe3da;border-radius:16px;background:#f8fcfa;box-shadow:0 8px 24px rgba(20,62,49,.06)';(document.querySelector('main')||document.body).appendChild(box);event('decision_pack_viewed',{price_gbp:19})}if(box.dataset.hqcState===state)return;box.dataset.hqcState=state;box.innerHTML=state==='paid'?detailedMarkup():offerMarkup();bind(box)}
async function verifyReturn(){const p=new URLSearchParams(location.search),session=p.get('session_id');if(p.get('decision_pack')!=='success'||!session)return;try{const r=await fetch(`/api/decision-pack/status?session_id=${encodeURIComponent(session)}&case_id=${encodeURIComponent(caseId)}`),d=await r.json();if(r.ok&&d.paid){setPaid(session);if(!localStorage.getItem(`hqcDecisionPackReported:${session}`)){localStorage.setItem(`hqcDecisionPackReported:${session}`,'1');event('decision_pack_payment_success',{amount_pence:d.amount_total||1900,currency:d.currency||'gbp'})}history.replaceState({},'',location.pathname);render()}}catch{}}
verifyReturn();new MutationObserver(render).observe(document.documentElement,{childList:true,subtree:true,characterData:true});setTimeout(render,1000);
})();