(()=>{
  const PENDING='hqc_pending_quotes',MODE='hqc_add_second',AUTO='hqc_auto_started';
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const read=(k,store=localStorage)=>{try{return JSON.parse(store.getItem(k)||'[]')}catch{return[]}};
  const readCase=()=>read('hqc_case'), readPending=()=>read(PENDING,sessionStorage);
  const absent=v=>v==null||v===''||/not evidenced|not found on quote/i.test(String(v));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const completeness=q=>{const items=[['Total price',q.price!=null&&Number(q.price)>0],['Exact heat-pump model',!absent(q.model)],['Nominal capacity stated',!absent(q.capacity)],['Whole-home heat loss',q.heatLossKw!=null&&Number.isFinite(Number(q.heatLossKw))],['Room-by-room heat loss',/provided/i.test(q.roomByRoom||'')&&!/not provided|not found/i.test(q.roomByRoom||'')],['Design outdoor temperature',q.designOutdoorC!=null&&Number.isFinite(Number(q.designOutdoorC))],['Design flow temperature',q.flowTemperatureC!=null&&Number.isFinite(Number(q.flowTemperatureC))],['Radiator / emitter treatment',!absent(q.emitterChanges)],['COP / SCOP evidence or claim stated',!absent(q.efficiency)],['MCS reference / claim stated',!absent(q.certification)]];return {score:items.filter(([,ok])=>ok).length,items};};
  const dedupe=quotes=>{const seen=new Set();return quotes.filter(q=>{const key=[q.fileName,q.installer,q.price,q.model,q.heatLossKw,q.flowTemperatureC].join('|');if(seen.has(key))return false;seen.add(key);return true;}).slice(0,4);};
  function directChild(parent,node){let n=node;while(n&&n.parentElement!==parent)n=n.parentElement;return n||node;}
  function homeParts(){const copy=qs('.copy');const img=qsa('img').find(x=>/homepage-graphic\.png/i.test(x.getAttribute('src')||''));if(!copy||!img)return null;let hero=copy.parentElement;while(hero&&hero!==document.body&&!hero.contains(img))hero=hero.parentElement;if(!hero||!hero.contains(img))return null;return {copy,img,hero,copyRoot:directChild(hero,copy),art:directChild(hero,img)};}
  function applyHome(){
    const p=homeParts();if(!p)return;const {copy,img,hero,copyRoot,art}=p,mobile=innerWidth<760,mode=mobile?'mobile-v8':'desktop-v8';if(hero.dataset.hqcMode===mode)return;hero.dataset.hqcMode=mode;
    hero.style.setProperty('display','grid','important');hero.style.setProperty('grid-template-columns',mobile?'1fr':'minmax(0,.88fr) minmax(0,1.12fr)','important');hero.style.setProperty('gap',mobile?'18px':'34px','important');hero.style.setProperty('align-items',mobile?'start':'center','important');hero.style.setProperty('padding',mobile?'18px 22px 22px':'42px 44px','important');
    [...hero.children].forEach(c=>c.style.setProperty('display',c===copyRoot||c===art?'block':'none','important'));
    copyRoot.style.setProperty('order','1','important');copyRoot.style.setProperty('width','100%','important');copyRoot.style.setProperty('min-width','0','important');copy.style.setProperty('display','block','important');copy.style.setProperty('margin','0','important');copy.style.setProperty('max-width',mobile?'none':'620px','important');
    const h=qs('h1,h2',copy),lead=qs('p',copy),btn=qs('button.primary',copy);
    if(h){h.textContent='Got a heat-pump quote? Check what’s missing before you sign.';h.style.setProperty('display','block','important');h.style.setProperty('visibility','visible','important');h.style.setProperty('font-size',mobile?'clamp(40px,10.8vw,58px)':'clamp(48px,5vw,68px)','important');h.style.setProperty('line-height','1.02','important');h.style.setProperty('letter-spacing','-.035em','important');h.style.setProperty('margin',mobile?'10px 0 14px':'0 0 16px','important');h.style.setProperty('font-weight','800','important');h.style.setProperty('color','#0b2548','important');}
    if(lead){lead.textContent='Upload your quote in seconds and we’ll highlight what’s included, what’s missing and how it compares — so you can make a confident decision.';lead.style.setProperty('font-size',mobile?'18px':'16px','important');lead.style.setProperty('line-height','1.45','important');lead.style.setProperty('margin','0 0 18px','important');lead.style.setProperty('color','#55657a','important');}
    let proof=qs('#hqc-landing-proof');if(!proof&&btn){proof=document.createElement('div');proof.id='hqc-landing-proof';proof.innerHTML='<span>✓ No account required</span><span>✓ No personal details needed</span><span>✓ One screenshot is enough</span>';btn.insertAdjacentElement('beforebegin',proof);}if(proof){proof.style.cssText=`margin:16px 0 18px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:${mobile?'12px':'10px'};font-size:${mobile?'12px':'11px'};line-height:1.35;color:#33475f`;}
    if(btn){btn.textContent='Check my quote — free  →';btn.style.setProperty('width',mobile?'100%':'min(430px,100%)','important');btn.style.setProperty('min-height',mobile?'60px':'54px','important');btn.style.setProperty('border-radius','8px','important');btn.style.setProperty('font-size',mobile?'18px':'inherit','important');btn.style.setProperty('font-weight','800','important');btn.style.setProperty('margin','0','important');if(mobile&&!qs('#hqc-cta-note')){const note=document.createElement('div');note.id='hqc-cta-note';note.textContent='Get an independent check in seconds.';note.style.cssText='text-align:center;font-size:12px;color:#6c7785;margin:7px 0 0';btn.insertAdjacentElement('afterend',note);}}
    art.style.setProperty('order','2','important');art.style.setProperty('width','100%','important');art.style.setProperty('overflow','hidden','important');art.style.setProperty('border-radius',mobile?'14px':'16px','important');art.style.setProperty('background','#eef8f4','important');art.style.setProperty('position','relative','important');art.style.setProperty('padding','0','important');art.style.setProperty('margin',mobile?'4px 0 0':'0','important');art.style.setProperty('aspect-ratio',mobile?'1.94 / 1':'1.15 / 1','important');art.style.setProperty('max-height',mobile?'none':'590px','important');
    img.style.setProperty('display','block','important');img.style.setProperty('position','absolute','important');img.style.setProperty('max-width','none','important');img.style.setProperty('height','auto','important');img.style.setProperty('transform','none','important');img.style.setProperty('object-fit','unset','important');img.style.setProperty('margin','0','important');if(mobile){img.style.setProperty('width','300%','important');img.style.setProperty('left','-94%','important');img.style.setProperty('top','-16%','important');}else{img.style.setProperty('width','175%','important');img.style.setProperty('left','-76%','important');img.style.setProperty('top','-7%','important');}
    img.alt='Heat-pump quote comparison showing price and heat-loss differences';
  }
  function optimiseUpload(){const card=qsa('.card').find(x=>/Add your quotes/i.test(qs('h1',x)?.textContent||''));if(!card||qs('#hqc-upload-help'))return;const intro=qs('h1',card)?.nextElementSibling;if(intro)intro.textContent='Start with one genuine installer quote. One clear screenshot or phone photo is enough to begin; you can compare another quote after the first check.';const drop=qs('.drop',card),fileInput=qs('input[type="file"]',card),manual=qsa('button,a',card).find(x=>/enter manually|manual entry|type.*manually/i.test(x.textContent||''));const help=document.createElement('div');help.id='hqc-upload-help';help.style.cssText='margin:16px 0;padding:16px;border-radius:11px;background:#eef8f4;border:1px solid #d7e9e2;color:#40516a;font-size:12px;line-height:1.5';help.innerHTML='<b style="display:block;color:#07503b;margin-bottom:5px;font-size:14px">Fastest way to start</b><span>Use a clear screenshot or phone photo showing the quote price and key design figures. You do not need to upload the whole document.</span><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button type="button" id="hqc-choose-file" style="border:0;border-radius:9px;background:#087f5b;color:white;padding:11px 14px;font-weight:800;cursor:pointer">Choose screenshot / photo →</button><button type="button" id="hqc-enter-manual" style="border:1px solid #afcfc4;border-radius:9px;background:white;color:#07503b;padding:11px 14px;font-weight:800;cursor:pointer">Enter figures manually</button></div><small style="display:block;margin-top:9px;color:#68778a">No account required. Uploaded images are processed transiently and are not intentionally stored. This check does not certify design, MCS status or grant eligibility.</small>';(drop||qs('h1',card))?.insertAdjacentElement(drop?'beforebegin':'afterend',help);qs('#hqc-choose-file')?.addEventListener('click',()=>fileInput?fileInput.click():drop?.dispatchEvent(new MouseEvent('click',{bubbles:true})));if(manual)qs('#hqc-enter-manual')?.addEventListener('click',()=>manual.click());else qs('#hqc-enter-manual')?.remove();}
  function mergeSecond(){if(sessionStorage.getItem(MODE)!=='1')return false;const pending=readPending(),current=readCase(),results=!!qs('.resultsTop');if(results&&pending.length&&current.length&&JSON.stringify(current)!==JSON.stringify(pending)){const merged=dedupe([...pending,...current]);if(merged.length>pending.length){localStorage.setItem('hqc_case',JSON.stringify(merged));sessionStorage.removeItem(PENDING);sessionStorage.removeItem(MODE);sessionStorage.removeItem(AUTO);location.reload();return true;}}if(!results&&current.length===0&&!sessionStorage.getItem(AUTO)){const start=qsa('button').find(x=>/check my heat-pump quotes|check my quote|get started/i.test(x.textContent||''));if(start){sessionStorage.setItem(AUTO,'1');start.click();}}return false;}
  function renderCompleteness(){const quotes=readCase(),facts=qs('.facts.panel');if(!facts||!quotes.length||qs('#hqc-completeness'))return;const section=document.createElement('section');section.id='hqc-completeness';section.className='panel';const cards=quotes.map((q,i)=>{const c=completeness(q),missing=c.items.filter(([,ok])=>!ok).map(([n])=>n),who=esc(q.installer||q.fileName||`Quote ${i+1}`);return `<article><small>EVIDENCE COMPLETENESS</small><h3>${who}</h3><p style="font-size:32px;font-weight:900;margin:6px 0;color:#00845c">${c.score}/10</p><p style="font-size:11px;color:#617187;margin:0 0 8px">documented</p>${missing.length?`<p style="font-size:11px;line-height:1.5"><b>Still missing:</b> ${missing.map(esc).join(', ')}</p>`:'<p style="font-size:11px;line-height:1.5"><b>All 10 evidence fields are stated.</b></p>'}</article>`;}).join('');const add=quotes.length===1&&quotes[0].isReal?'<div class="seoCta"><h2>Have another quote?</h2><p>Add it and Home Quote Check will show where the installers disagree.</p><button id="hqc-add-second" class="primary">Add another quote →</button></div>':'';section.innerHTML=`<h2>Quote evidence completeness</h2><p style="color:#617187;line-height:1.55"><b>This measures what each quote documents, not whether the design is correct.</b> It does not score sizing quality, MCS status or Boiler Upgrade Scheme eligibility.</p><div class="factCards">${cards}</div>${add}`;facts.parentNode.insertBefore(section,facts);qs('#hqc-add-second')?.addEventListener('click',()=>{sessionStorage.setItem(PENDING,JSON.stringify(quotes));sessionStorage.setItem(MODE,'1');sessionStorage.removeItem(AUTO);qsa('button').find(x=>/check different quotes/i.test(x.textContent||''))?.click();});}
  function strengthenQuestions(){const panel=qs('.questions');if(!panel||panel.dataset.hqcEnhanced==='1')return;const btn=qs('button.primary',panel);if(!btn)return;panel.dataset.hqcEnhanced='1';const intro=document.createElement('div');intro.className='evidenceState';intro.innerHTML='<b>TAKE THE EVIDENCE BACK TO THE INSTALLER</b><p>Copy these neutral clarification questions into email, WhatsApp or the installer’s portal. They contain no customer details or source quote documents.</p>';qs('h2',panel)?.insertAdjacentElement('afterend',intro);if(/copy questions/i.test(btn.textContent||''))btn.textContent='Copy questions to send →';}
  let ticking=false;function tick(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;applyHome();optimiseUpload();if(mergeSecond())return;renderCompleteness();strengthenQuestions();});}
  new MutationObserver(tick).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',()=>{const h=homeParts()?.hero;if(h)delete h.dataset.hqcMode;tick();},{passive:true});addEventListener('storage',tick);tick();
})();
