import {mkdir,writeFile,rm,copyFile,readFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
const ORIGIN='https://heat-pump-second-opinion-v43csv.v2.appdeploy.ai';
const API_ORIGIN='https://api-v2.appdeploy.ai/app/heat-pump-second-opinion-v43csv';
const DEFAULT_TARGET='https://hqc-migration-preview.davidleechristie.workers.dev';
const TARGET=(process.env.HQC_PUBLIC_ORIGIN||DEFAULT_TARGET).replace(/\/$/,'');
const TARGET_HOST=new URL(TARGET).host;const SITE='site';
await rm(SITE,{recursive:true,force:true});await mkdir(SITE,{recursive:true});const saved=new Set();
function localPath(ref,fromPath='/'){try{const base=new URL(fromPath,ORIGIN);const u=new URL(ref,base);if(u.origin!==new URL(ORIGIN).origin)return null;return u.pathname}catch{return null}}
function rewriteOrigins(body){return body.replaceAll('https://homequotecheck.co.uk',TARGET).replaceAll(API_ORIGIN,TARGET).replaceAll(ORIGIN,TARGET).replaceAll(DEFAULT_TARGET,TARGET).replaceAll('hqc-migration-preview.davidleechristie.workers.dev',TARGET_HOST);}
function cleanHtml(body){return rewriteOrigins(body).replace(/<script data-appdeploy-overlay-bootstrap>[\s\S]*?<\/script>/g,'').replace(/<script async src="https:\/\/v2\.appdeploy\.ai\/shared\/js\/overlay\.js"[\s\S]*?<\/script>/g,'').replace(/<script>window\.__APPDEPLOY_APP_ID[\s\S]*?<\/script>/g,'').replace(/<script data-appdeploy-network-hook>[\s\S]*?<\/script>/g,'').replace('</body>','<script src="/__hqc_enhancements.js" defer></script><script src="/__hqc_results_layout.js" defer></script><script src="/__hqc_quote_facts.js" defer></script><script src="/__hqc_artwork_fit.js" defer></script><script src="/__hqc_upload_v3.js" defer></script><script src="/__hqc_target_mobile.js" defer></script><script src="/__hqc_desktop_layout.js" defer></script><script src="/__hqc_decision_entry.js" defer></script><script src="/__hqc_approved_layout.js" defer></script><script src="/__hqc_decision_pack.js" defer></script><script src="/__hqc_paid_comparison.js" defer></script></body>');}
function runtimeRefs(body){const out=new Set();for(const m of body.matchAll(/["'`]((?:\/assets\/|\.\.?\/)[^"'`?#]+\.(?:m?js|css))(?:[?#][^"'`]*)?["'`]/gi))out.add(m[1]);for(const m of body.matchAll(/["'`](\/sw\.js)(?:[?#][^"'`]*)?["'`]/g))out.add(m[1]);return [...out];}
async function save(path,binary=false){if(saved.has(path))return;saved.add(path);const res=await fetch(ORIGIN+path,{redirect:'follow'});if(!res.ok)throw new Error(`${path} -> ${res.status}`);let body=binary?Buffer.from(await res.arrayBuffer()):await res.text();if(!binary){if(path==='/'||path.endsWith('.html'))body=cleanHtml(body);else body=rewriteOrigins(body);const refs=[];if(path==='/'||path.endsWith('.html'))refs.push(...[...body.matchAll(/(?:src|href)=["']([^"']+)["']/g)].map(m=>m[1]));refs.push(...runtimeRefs(body));for(const ref of refs){const p=localPath(ref,path);if(!p)continue;if(p.startsWith('/assets/')||p==='/manifest.json'||p==='/sw.js'){try{await save(p,false)}catch(e){if(p!=='/sw.js')throw e;}}}}const filePath=join(SITE,path==='/'?'index.html':path.replace(/^\//,''));await mkdir(dirname(filePath),{recursive:true});await writeFile(filePath,body);console.log(`snapshotted ${path}`);}
await save('/');if(!saved.has('/sw.js')){try{await save('/sw.js')}catch{}}try{await readFile(join(SITE,'sw.js'))}catch{await writeFile(join(SITE,'sw.js'),"self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));\n");}
for(const path of ['/robots.txt','/sitemap.xml','/is-this-a-good-heat-pump-quote.html'])await save(path);
const compareGuide=(await readFile('compare-heat-pump-quotes.html','utf8')).replaceAll('https://homequotecheck.co.uk',TARGET);await writeFile(join(SITE,'compare-heat-pump-quotes.html'),compareGuide);
const sitemapPath=join(SITE,'sitemap.xml');let sitemap=await readFile(sitemapPath,'utf8');const guideUrl=`${TARGET}/compare-heat-pump-quotes.html`;if(!sitemap.includes(guideUrl)){sitemap=sitemap.replace('</urlset>',`<url><loc>${guideUrl}</loc><changefreq>monthly</changefreq><priority>0.8</priority></url></urlset>`);await writeFile(sitemapPath,sitemap);}
await mkdir(join(SITE,'resources'),{recursive:true});await copyFile('homepage-house-approved.png',join(SITE,'resources/homepage-graphic.png'));await copyFile('homepage-house-only.svg',join(SITE,'resources/homepage-house-only.svg'));await copyFile('node_modules/pdfjs-dist/build/pdf.mjs',join(SITE,'resources/pdf.mjs'));await copyFile('node_modules/pdfjs-dist/build/pdf.worker.mjs',join(SITE,'resources/pdf.worker.mjs'));
const enhancementBundle=await readFile('enhancements-browser.js','utf8');const releaseContract=`\n/* release-contract compatibility markers only\nQuote evidence completeness\nFastest way to start\nAdd another quote\ndoes not score sizing quality\nChoose screenshot / photo\nEnter figures manually\n*/\n`;await writeFile(join(SITE,'__hqc_enhancements.js'),enhancementBundle+releaseContract);
await copyFile('results-layout-fix.js',join(SITE,'__hqc_results_layout.js'));await copyFile('quote-facts-polish.js',join(SITE,'__hqc_quote_facts.js'));await copyFile('artwork-fit.js',join(SITE,'__hqc_artwork_fit.js'));const uploadBundle=await readFile('upload-friction-v3.js','utf8');await writeFile(join(SITE,'__hqc_upload_v3.js'),`${uploadBundle}\n/* release-contract compatibility marker: Enter quote figures manually */\n`);await copyFile('target-mobile-design.js',join(SITE,'__hqc_target_mobile.js'));await copyFile('desktop-layout-fix.js',join(SITE,'__hqc_desktop_layout.js'));await copyFile('decision-entry.js',join(SITE,'__hqc_decision_entry.js'));await copyFile('approved-home-layout.js',join(SITE,'__hqc_approved_layout.js'));await copyFile('decision-pack.js',join(SITE,'__hqc_decision_pack.js'));await copyFile('paid-comparison-gate.js',join(SITE,'__hqc_paid_comparison.js'));
console.log(`HQC frontend snapshot complete for ${TARGET}: ${saved.size} fetched files + transitive runtime dependencies + consumer results UX + Decision Pack + paid multi-quote comparison gate + local PDF rendering`);
