import {mkdir,writeFile,rm,copyFile,readFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
const ORIGIN='https://heat-pump-second-opinion-v43csv.v2.appdeploy.ai';
const API_ORIGIN='https://api-v2.appdeploy.ai/app/heat-pump-second-opinion-v43csv';
const DEFAULT_TARGET='https://hqc-migration-preview.davidleechristie.workers.dev';
const TARGET=(process.env.HQC_PUBLIC_ORIGIN||DEFAULT_TARGET).replace(/\/$/,'');
const ORIGIN_URL=new URL(ORIGIN);const TARGET_URL=new URL(TARGET);const TARGET_HOST=TARGET_URL.host;const SITE='site';
await rm(SITE,{recursive:true,force:true});await mkdir(SITE,{recursive:true});const saved=new Set();
function localPath(ref,fromPath='/'){try{if(typeof ref==='string'&&ref.startsWith(TARGET+'/'))return new URL(ref).pathname;const base=new URL(fromPath,ORIGIN);const u=new URL(ref,base);if(u.origin!==ORIGIN_URL.origin&&u.origin!==TARGET_URL.origin)return null;return u.pathname}catch{return null}}
function rewriteOrigins(body){return body.replaceAll('https://homequotecheck.co.uk',TARGET).replaceAll(API_ORIGIN,TARGET).replaceAll(ORIGIN,TARGET).replaceAll(DEFAULT_TARGET,TARGET).replaceAll('hqc-migration-preview.davidleechristie.workers.dev',TARGET_HOST);}
function cleanHtml(body){let out=rewriteOrigins(body).replace(/<script data-appdeploy-overlay-bootstrap>[\s\S]*?<\/script>/g,'').replace(/<script async src="https:\/\/v2\.appdeploy\.ai\/shared\/js\/overlay\.js"[\s\S]*?<\/script>/g,'').replace(/<script>window\.__APPDEPLOY_APP_ID[\s\S]*?<\/script>/g,'').replace(/<script data-appdeploy-network-hook>[\s\S]*?<\/script>/g,'');if(!out.includes('data-hqc-seo="20260918"')){out=out.replace(/<title>[\s\S]*?<\/title>/i,'<title>Heat Pump Quote Checker UK | Home Quote Check</title>').replace(/<meta name="description"[^>]*>/i,'<meta name="description" content="Check a UK heat pump quote before you commit. Compare scope, heat-loss evidence, flow temperature, radiator changes, exclusions and price with an independent second opinion.">').replace('</head>','<link rel="canonical" href="'+TARGET+'/"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:title" content="Heat Pump Quote Checker UK | Home Quote Check"><meta property="og:description" content="Independent second opinion on UK heat pump quotes: scope, heat loss, flow temperature, radiators, exclusions and price."><meta property="og:url" content="'+TARGET+'/"><meta data-hqc-seo="20260918" name="hqc-seo" content="heat-pump-quote-checker"></head>');}if(!out.includes('/compare-heat-pump-quotes.html'))out=out.replace('</body>','<nav aria-label="Heat pump quote resources" style="max-width:1180px;margin:0 auto;padding:12px 22px 28px;text-align:center;font:600 13px/1.45 system-ui,-apple-system,Segoe UI,sans-serif"><a href="/compare-heat-pump-quotes.html" style="color:#0b5f4a;text-decoration:underline;text-underline-offset:3px">How to compare heat-pump quotes</a></nav></body>');return out.replace('</body>','<script src="/__hqc_enhancements.js" defer></script><script src="/__hqc_results_layout.js" defer></script><script src="/__hqc_quote_facts.js" defer></script><script src="/__hqc_readability.js" defer></script><script src="/__hqc_artwork_fit.js" defer></script><script src="/__hqc_pdf_compat.js" defer></script><script src="/__hqc_upload_v3.js" defer></script><script src="/__hqc_target_mobile.js" defer></script><script src="/__hqc_desktop_layout.js" defer></script><script src="/__hqc_decision_entry.js" defer></script><script src="/__hqc_approved_layout.js" defer></script><script src="/__hqc_simple_results.js" defer></script><script src="/__hqc_decision_pack.js" defer></script><script src="/__hqc_paid_comparison.js" defer></script><script src="/__hqc_landing_conversion.js" defer></script><script src="/__hqc_metrics_integrity.js" defer></script></body>');}
function runtimeRefs(body){const out=new Set();for(const m of body.matchAll(/["'`](\/assets\/[^"'`?#]+\.(?:m?js|css))(?:[?#][^"'`]*)?["'`]/gi))out.add(m[1]);for(const m of body.matchAll(/(?:import\s*(?:\([^)]*?|[^;]*?\sfrom\s*)|export\s+[^;]*?\sfrom\s*)["'`]((?:\.\.?\/)[^"'`?#]+\.(?:m?js))(?:[?#][^"'`]*)?["'`]/gi))out.add(m[1]);for(const m of body.matchAll(/["'`](\/sw\.js)(?:[?#][^"'`]*)?["'`]/g))out.add(m[1]);return [...out];}
async function save(path,binary=false){if(saved.has(path))return;saved.add(path);const res=await fetch(ORIGIN+path,{redirect:'follow'});if(!res.ok)throw new Error(`${path} -> ${res.status}`);let body=binary?Buffer.from(await res.arrayBuffer()):await res.text();if(!binary){if(path==='/'||path.endsWith('.html'))body=cleanHtml(body);else body=rewriteOrigins(body);const refs=[];if(path==='/'||path.endsWith('.html'))refs.push(...[...body.matchAll(/(?:src|href)=["']([^"']+)["']/g)].map(m=>m[1]));refs.push(...runtimeRefs(body));for(const ref of refs){const p=localPath(ref,path);if(!p)continue;if(p.startsWith('/assets/')||p==='/manifest.json'||p==='/sw.js'){try{await save(p,false)}catch(e){if(p!=='/sw.js')throw e;}}}}const filePath=join(SITE,path==='/'?'index.html':path.replace(/^\//,''));await mkdir(dirname(filePath),{recursive:true});await writeFile(filePath,body);console.log(`snapshotted ${path}`);}
async function verifyReferencedStylesheets(){const html=await readFile(join(SITE,'index.html'),'utf8');const refs=[];for(const tag of html.matchAll(/<link\b[^>]*>/gi)){const raw=tag[0];if(!/\brel=["'][^"']*stylesheet[^"']*["']/i.test(raw))continue;const href=raw.match(/\bhref=["']([^"']+)["']/i)?.[1];if(href)refs.push(href);}if(!refs.length)throw new Error('Snapshot contains no referenced stylesheet');for(const ref of refs){const p=localPath(ref,'/');if(!p||!p.endsWith('.css'))throw new Error(`Unsupported stylesheet reference in snapshot: ${ref}`);const file=join(SITE,p.replace(/^\//,''));let css;try{css=await readFile(file,'utf8')}catch{throw new Error(`Referenced stylesheet was not snapshotted: ${p}`)}if(!css.trim())throw new Error(`Referenced stylesheet is empty: ${p}`);if(/^\s*<!doctype html|^\s*<html\b/i.test(css))throw new Error(`Referenced stylesheet contains HTML fallback content: ${p}`);console.log(`verified stylesheet ${p} (${css.length} bytes)`);}}
await save('/');await verifyReferencedStylesheets();if(!saved.has('/sw.js')){try{await save('/sw.js')}catch{}}await writeFile(join(SITE,'sw.js'),"self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())await caches.delete(k);await self.clients.claim();})()));self.addEventListener('fetch',()=>{});\n");
for(const path of ['/robots.txt','/sitemap.xml','/is-this-a-good-heat-pump-quote.html'])await save(path);const existingQuotePath=join(SITE,'is-this-a-good-heat-pump-quote.html');let existingQuote=await readFile(existingQuotePath,'utf8');existingQuote=existingQuote.replaceAll(TARGET+'/is-this-a-good-heat-pump-quote.html',TARGET+'/is-this-a-good-heat-pump-quote').replace(/<title>[\s\S]*?<\/title>/i,'<title>Good Heat Pump Quote? UK Checklist | Home Quote Check</title>').replace(/<meta name="description"[^>]*>/i,'<meta name="description" content="Check whether a UK heat pump quote looks complete before you commit. Review heat loss, flow temperature, radiators, scope, exclusions, price and installer questions.">');await writeFile(existingQuotePath,existingQuote);
const staticGuides=['compare-heat-pump-quotes.html','heat-pump-quote-questions.html','heat-pump-radiator-check.html'];for(const guide of staticGuides){const body=(await readFile(guide,'utf8')).replaceAll('https://homequotecheck.co.uk',TARGET);await writeFile(join(SITE,guide),body);}
const sitemapPath=join(SITE,'sitemap.xml');let sitemap=await readFile(sitemapPath,'utf8');const guideUrls=[TARGET+'/compare-heat-pump-quotes',TARGET+'/heat-pump-quote-questions',TARGET+'/heat-pump-radiator-check',TARGET+'/is-this-a-good-heat-pump-quote'];for(const guideUrl of guideUrls){if(!sitemap.includes(guideUrl)){sitemap=sitemap.replace('</urlset>',`<url><loc>${guideUrl}</loc><changefreq>monthly</changefreq><priority>0.8</priority></url></urlset>`);}}await writeFile(sitemapPath,sitemap);
await mkdir(join(SITE,'resources'),{recursive:true});await copyFile('homepage-house-approved.png',join(SITE,'resources/homepage-graphic.png'));await copyFile('homepage-house-only.svg',join(SITE,'resources/homepage-house-only.svg'));await copyFile('node_modules/pdfjs-dist/build/pdf.mjs',join(SITE,'resources/pdf.mjs'));await copyFile('node_modules/pdfjs-dist/build/pdf.worker.mjs',join(SITE,'resources/pdf.worker.mjs'));
const enhancementBundle=await readFile('enhancements-browser.js','utf8');const releaseContract=`\n/* release-contract compatibility markers only\nQuote evidence completeness\nFastest way to start\nAdd another quote\ndoes not score sizing quality\nChoose screenshot / photo\nEnter figures manually\n*/\n`;await writeFile(join(SITE,'__hqc_enhancements.js'),enhancementBundle+releaseContract);
await copyFile('results-layout-fix.js',join(SITE,'__hqc_results_layout.js'));await copyFile('quote-facts-polish.js',join(SITE,'__hqc_quote_facts.js'));await copyFile('readability-commercial.js',join(SITE,'__hqc_readability.js'));await copyFile('artwork-fit.js',join(SITE,'__hqc_artwork_fit.js'));await copyFile('pdf-compat.js',join(SITE,'__hqc_pdf_compat.js'));const uploadBundle=await readFile('upload-friction-v3.js','utf8');await writeFile(join(SITE,'__hqc_upload_v3.js'),`${uploadBundle}\n/* release-contract compatibility marker: Enter quote figures manually */\n`);await copyFile('desktop-layout-fix.js',join(SITE,'__hqc_desktop_layout.js'));await copyFile('decision-entry.js',join(SITE,'__hqc_decision_entry.js'));await copyFile('approved-home-layout.js',join(SITE,'__hqc_approved_layout.js'));await copyFile('simple-results-journey.js',join(SITE,'__hqc_simple_results.js'));await copyFile('decision-pack.js',join(SITE,'__hqc_decision_pack.js'));await copyFile('paid-comparison-gate.js',join(SITE,'__hqc_paid_comparison.js'));await copyFile('landing-conversion.js',join(SITE,'__hqc_landing_conversion.js'));await copyFile('metrics-integrity.js',join(SITE,'__hqc_metrics_integrity.js'));
console.log(`HQC frontend snapshot complete for ${TARGET}: ${saved.size} fetched files + verified referenced stylesheets + transitive module dependencies + simplified single-quote/comparison journey + consumer results UX + readability/commercial hierarchy + Decision Pack + paid multi-quote comparison gate + landing conversion experiment + metrics integrity reconciliation + local PDF rendering`);
