name = "hqc-migration-preview"
main = "worker.js"
compatibility_date = "2026-09-08"
workers_dev = true
routes = [
  { pattern = "cf-preview.homequotecheck.co.uk", custom_domain = true }
]

[[durable_objects.bindings]]
name = "HQC_METRICS"
class_name = "HqcMetrics"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HqcMetrics"]

[assets]
directory = "./site"
binding = "ASSETS"
not_found_handling = "single-page-application"
